---
abstract: 'A Log::Log4perl wrapper for use with Clustericious.'
author:
  - 'Brian Duggan <brian.duggan@nasa.gov>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious-Log
provides:
  Clustericious::Log:
    file: lib/Clustericious/Log.pm
    version: 0.10
requires:
  File::ReadBackwards: 0
  List::Util: 0
  Log::Log4perl: 0
  MojoX::Log::Log4perl: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
