---
abstract: 'A Log::Log4perl wrapper for use with Clustericious.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious-Log
requires:
  Carp: 0
  File::HomeDir: 0.91
  File::ReadBackwards: 0
  List::Util: 0
  Log::Log4perl: 0
  Log::Log4perl::Appender::TAP: 0
  MojoX::Log::Log4perl: 0
  Test::Builder::Module: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/clustericious-log/issues
  homepage: http://perl.wdlabs.com/Clustericious-Log/
  repository: git://github.com/plicease/clustericious-log.git
version: 0.12
